#!/usr/bin/env bash
# Boot four AXL daemons (one per agent) in the background.
#
# Assumes the AXL binary is at $AXL_BIN (default: ~/shiva/axl/node).
# Each daemon gets:
#   - its own data dir under ./nodes/<role>/data
#   - a unique tls/api/tcp port triple
#   - the ed25519 keypair already generated by setup at ./nodes/<role>/private.pem
#
# Logs land in ./logs/<role>.log. Stop everything with `pkill -f $AXL_BIN`.

set -eu

cd "$(dirname "$0")"

AXL_BIN="${AXL_BIN:-$HOME/shiva/axl/node}"
if [ ! -x "$AXL_BIN" ]; then
  echo "AXL binary not found or not executable at $AXL_BIN" >&2
  echo "Set AXL_BIN=/path/to/axl-node and re-run, or build it first:" >&2
  echo "  cd ~/shiva/axl && go build -o node ./cmd/node" >&2
  exit 1
fi

mkdir -p logs

start_node() {
  local role="$1" tls_port="$2" api_port="$3" tcp_port="$4"
  local node_dir="./nodes/$role"
  local data_dir="$node_dir/data"
  local cfg="$node_dir/node-config.json"
  mkdir -p "$data_dir"

  cat > "$cfg" <<JSON
{
  "private_key_file": "$(pwd)/$node_dir/private.pem",
  "data_dir":         "$(pwd)/$data_dir",
  "tls_port":         $tls_port,
  "api_port":         $api_port,
  "tcp_port":         $tcp_port,
  "bootstrap_peers":  []
}
JSON

  local log="logs/$role.log"
  echo "starting axl-$role  api:$api_port  tls:$tls_port  tcp:$tcp_port  -> $log"
  nohup "$AXL_BIN" -config "$cfg" >"$log" 2>&1 &
}

start_node pm       9101 9001 7001
start_node alm      9102 9002 7002
start_node router   9103 9003 7003
start_node executor 9104 9004 7004

echo
echo "All four AXL daemons started in background."
echo "Tail logs:  tail -f logs/*.log"
echo "Stop all:   pkill -f $AXL_BIN"
