[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 1_000_000
via_ir = false
remappings = [
  "forge-std/=lib/forge-std/src/",
  "permit2/=src/interfaces/",
]

[profile.fork]
fuzz = { runs = 32 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
base = "${RPC_BASE}"
unichain = "${RPC_UNICHAIN}"
sepolia = "${RPC_SEPOLIA}"
